Repository nromanen/Schedule, pull requests merged in 2021-11, with the labels that each got.

#83 Backend - Added posibility to get, create, update custom group order
  .gitignore
  build.gradle
  src/main/java/com/softserve/controller/GroupController.java
  src/main/java/com/softserve/entity/Group.java
  src/main/java/com/softserve/exception/SortingOrderNotExistsException.java
  src/main/java/com/softserve/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/softserve/repository/GroupRepository.java
  src/main/java/com/softserve/repository/impl/GroupRepositoryImpl.java
  src/main/java/com/softserve/service/GroupService.java
  src/main/java/com/softserve/service/impl/GroupServiceImpl.java
  src/test/java/com/softserve/controller/GroupControllerTest.java
  src/test/java/com/softserve/service/GroupServiceTest.java
  src/test/resources/create-groups-before.sql
Labels: backend

#92 Backend/FixTeacherMapper
  src/main/java/com/softserve/mapper/TeacherMapper.java
Labels: backend

#86 Backend/FixAddGroupsToSemester
  src/main/java/com/softserve/controller/SemesterController.java
  src/main/java/com/softserve/repository/GroupRepository.java
  src/main/java/com/softserve/repository/impl/GroupRepositoryImpl.java
  src/main/java/com/softserve/service/GroupService.java
  src/main/java/com/softserve/service/SemesterService.java
  src/main/java/com/softserve/service/impl/GroupServiceImpl.java
  src/main/java/com/softserve/service/impl/SemesterServiceImpl.java
  src/test/java/com/softserve/service/GroupServiceTest.java
  src/test/java/com/softserve/service/SemesterServiceTest.java
Labels: backend

#98 Backend/FixGroupLessonUpdate
  src/main/java/com/softserve/dto/LessonBaseDTO.java
  src/main/java/com/softserve/mapper/LessonInfoMapper.java
  src/main/java/com/softserve/repository/LessonRepository.java
  src/main/java/com/softserve/repository/impl/LessonRepositoryImpl.java
  src/main/java/com/softserve/service/impl/LessonServiceImpl.java
Labels: backend

#96 Backend/Add disable field in Teacher and Group DTO
  frontend/package.json
  frontend/src/helper/axios.js
  schedule_logs/log.log
  src/main/java/com/softserve/dto/GroupDTO.java
  src/main/java/com/softserve/dto/TeacherDTO.java
  src/main/resources/hibernate.properties
  src/test/java/com/softserve/controller/DepartmentControllerTest.java
  src/test/java/com/softserve/controller/GroupControllerTest.java
  src/test/java/com/softserve/controller/StudentControllerTest.java
  src/test/java/com/softserve/controller/TeacherControllerTest.java
  src/test/java/com/softserve/controller/UserControllerTest.java
  src/test/java/com/softserve/service/TeacherServiceTest.java
  src/test/resources/create-teachers-before.sql
  src/test/resources/hibernatetest.properties
Labels: backend

#124 Backend/BugFix/FixGroupControllerEndpoints
  src/main/java/com/softserve/controller/GroupController.java
  src/main/java/com/softserve/dto/GroupDTO.java
Labels: bug, backend

#125 Backend/BugFix/FixLessonInfoMapper
  src/main/java/com/softserve/mapper/LessonInfoMapper.java
Labels: bug, backend

#135 TS-hepler-tests
  frontend/src/components/EditCurrentSchedule/EditCurrentSchedule.scss
  frontend/src/components/GroupSchedulePage/GroupSchedulePage.js
  frontend/src/components/LanguageSelector/LanguageSelector.js
  frontend/src/helper/ReduxFormSelect.js
  frontend/src/helper/disableComponent.js
  frontend/src/helper/disableComponent.test.js
  frontend/src/helper/getHref.js
  frontend/src/helper/getHref.test.js
  frontend/src/helper/getScheduleType.test.js
  frontend/src/helper/handleFormSubmit.test.js
  frontend/src/helper/prepareLessonCell.js
  frontend/src/helper/prepareLessonCell.test.js
  frontend/src/helper/prepareTeacherCell.js
  frontend/src/helper/prepareTeacherCell.test.js
  frontend/src/helper/renderSchedule.js
  frontend/src/i18n.js
  frontend/src/share/DialogWindows/dialogMapper.js
Labels: frontend

#119 Backend/fixed all test
  src/test/java/com/softserve/service/LessonServiceTest.java
  src/test/java/com/softserve/service/ScheduleServiceTest.java
  src/test/java/com/softserve/service/SemesterServiceTest.java
Labels: backend

#134 test: add to setLink, shortTitle, sortArray, strings
  frontend/src/helper/setLink.test.js
  frontend/src/helper/shortTitle.test.js
  frontend/src/helper/sortArray.test.js
  frontend/src/helper/sortGroup.js
  frontend/src/helper/strings.test.js
  frontend/src/reducers/groups.js
  frontend/src/services/groupService.js
Labels: frontend

#128 Backend/BugFix/CustomGroupOrder
  src/main/java/com/softserve/entity/Group.java
  src/main/java/com/softserve/repository/GroupRepository.java
  src/main/java/com/softserve/repository/impl/GroupRepositoryImpl.java
  src/main/java/com/softserve/service/impl/GroupServiceImpl.java
  src/test/java/com/softserve/controller/GroupControllerTest.java
  src/test/java/com/softserve/service/GroupServiceTest.java
Labels: backend

#140 fix:Add missed dependency in package.json
  frontend/package.json
Labels: frontend
