Repository nromanen/Schedule, pull requests merged in 2021-12, with the labels that each got.

#118 [Backend]fix copy semester, and add Test
  src/main/java/com/softserve/controller/ScheduleController.java
  src/main/java/com/softserve/controller/SemesterController.java
  src/main/java/com/softserve/repository/impl/ScheduleRepositoryImpl.java
  src/main/java/com/softserve/service/SemesterService.java
  src/main/java/com/softserve/service/impl/ScheduleServiceImpl.java
  src/main/java/com/softserve/service/impl/SemesterServiceImpl.java
  src/test/java/com/softserve/controller/SemesterControllerTest.java
  src/test/resources/create-semesters-before.sql
Labels: backend

#143 TS-fix-copy-and-select-groups-in-Semester-page
  frontend/package.json
  frontend/public/assets/i18n/translations/en/formElements.json
  frontend/public/assets/i18n/translations/uk/formElements.json
  frontend/src/components/EditCurrentSchedule/EditCurrentSchedulePage.js
  frontend/src/components/RoomsPage/RoomForm/RoomForm.js
  frontend/src/components/RoomsPage/RoomForm/RoomForm.scss
  frontend/src/components/Semester/SemesterForm/SemesterForm.scss
  frontend/src/components/Semester/SemesterList/SemesterCopyForm/SemesterSelect.js
  frontend/src/components/Semester/SemesterPage.js
  frontend/src/components/Semester/SemesterSidebar.js
  frontend/src/constants/axios.js
  frontend/src/containers/EditCurrentSchedule/EditCurrentSchedulePage.js
  frontend/src/reducers/rooms.js
  frontend/src/sagas/rooms.js
  frontend/src/sagas/semesters.js
  frontend/src/services/roomService.js
  frontend/src/services/roomTypesService.js
  frontend/src/services/semesterService.js
Labels: ready to review, frontend

#142 Ts-fix-move-students
  frontend/public/assets/i18n/translations/en/formElements.json
  frontend/public/assets/i18n/translations/en/serviceMessages.json
  frontend/public/assets/i18n/translations/uk/formElements.json
  frontend/public/assets/i18n/translations/uk/serviceMessages.json
  frontend/src/actions/actionsType.js
  frontend/src/actions/students.js
  frontend/src/constants/axios.js
  frontend/src/constants/translationLabels/formElements.js
  frontend/src/constants/translationLabels/serviceMessages.js
  frontend/src/reducers/students.js
  frontend/src/sagas/student.js
  frontend/src/share/DialogWindows/_dialogWindows/MovingGroupsDialog.js
Labels: ready to review, frontend

#145 Ts drag and drop group
  frontend/public/assets/i18n/translations/en/common.json
  frontend/public/assets/i18n/translations/en/formElements.json
  frontend/public/assets/i18n/translations/uk/common.json
  frontend/public/assets/i18n/translations/uk/formElements.json
  frontend/src/actions/actionsType.js
  frontend/src/actions/groups.js
  frontend/src/components/AddGroupForm/AddGroupForm.js
  frontend/src/components/GroupPage/GroupCard/GroupCard.scss
  frontend/src/components/GroupPage/GroupList.js
  frontend/src/components/GroupPage/GroupPage.scss
  frontend/src/constants/axios.js
  frontend/src/constants/translationLabels/common.js
  frontend/src/constants/translationLabels/formElements.js
  frontend/src/containers/GroupPage/GroupForm.js
  frontend/src/containers/GroupPage/GroupPage.js
  frontend/src/helper/sortGroup.js
  frontend/src/reducers/groups.js
  frontend/src/sagas/group.js
  frontend/src/share/DraggableCard/DraggableCard.js
  frontend/src/share/DraggableCard/DraggableCard.scss
Labels: ready to review, frontend

#155 TS-testing-components-for-BusyRooms-page
  frontend/src/components/BusyRoomsPage/BustRoomsTable/BusyRoomsTable.test.js
  frontend/src/components/BusyRoomsPage/TableItem/GroupTitle.test.js
  frontend/src/components/BusyRoomsPage/TableItem/TableItem.js
  frontend/src/components/BusyRoomsPage/TableItem/TableItem.test.js
Labels: frontend

#149 Backend/BugFix/GroupedLessonUpdate
  src/main/java/com/softserve/repository/impl/LessonRepositoryImpl.java
  src/main/java/com/softserve/service/impl/LessonServiceImpl.java
Labels: bug, backend

#160 tested sortString, urlUtils utils
  frontend/src/utils/sortStrings.test.js
  frontend/src/utils/urlUtils.test.js
Labels: frontend

#146 Backend/import teacher
  src/main/java/com/softserve/controller/TeacherController.java
  src/main/java/com/softserve/dto/TeacherImportDTO.java
  src/main/java/com/softserve/dto/TeacherStatus.java
  src/main/java/com/softserve/mapper/TeacherMapper.java
  src/main/java/com/softserve/repository/TeacherRepository.java
  src/main/java/com/softserve/repository/impl/TeacherRepositoryImpl.java
  src/main/java/com/softserve/service/TeacherService.java
  src/main/java/com/softserve/service/impl/TeacherServiceImpl.java
  src/main/java/com/softserve/service/impl/UserServiceImpl.java
  src/main/java/com/softserve/util/CsvFileParser.java
  src/test/java/com/softserve/controller/TeacherControllerTest.java
  src/test/resources/create-teachers-before.sql
  src/test/resources/test_teachers.csv
Labels: ready to review, backend

#163 Back end/fix/get all semesters
  src/main/java/com/softserve/controller/LessonController.java
  src/main/java/com/softserve/controller/SemesterController.java
  src/main/java/com/softserve/entity/Semester.java
  src/main/java/com/softserve/mapper/GroupMapper.java
  src/main/java/com/softserve/mapper/LessonInfoMapper.java
  src/main/java/com/softserve/repository/impl/LessonRepositoryImpl.java
  src/main/java/com/softserve/repository/impl/SemesterRepositoryImpl.java
  src/main/java/com/softserve/service/GroupService.java
  src/main/java/com/softserve/service/impl/GroupServiceImpl.java
  src/main/java/com/softserve/service/impl/LessonServiceImpl.java
  src/main/java/com/softserve/service/impl/SemesterServiceImpl.java
  src/test/java/com/softserve/controller/LessonsControllerTest.java
  src/test/java/com/softserve/controller/SemesterControllerTest.java
  src/test/java/com/softserve/service/GroupServiceTest.java
  src/test/java/com/softserve/service/SemesterServiceTest.java
  src/test/resources/create-semesters-before.sql
Labels: backend

#129 Backend/RefactorScheduleController
  src/main/java/com/softserve/controller/ScheduleController.java
  src/main/java/com/softserve/dto/DaysOfWeekWithClassesForRoomDTO.java
  src/main/java/com/softserve/dto/LessonsInRoomScheduleDTO.java
  src/main/java/com/softserve/dto/LessonsListInRoomScheduleDTO.java
  src/main/java/com/softserve/dto/ScheduleForRoomDTO.java
  src/main/java/com/softserve/dto/SchedulesAtDayOfWeek.java
  src/main/java/com/softserve/dto/SchedulesInRoomDTO.java
  src/main/java/com/softserve/mapper/ConverterToSchedulesInRoom.java
  src/main/java/com/softserve/mapper/GroupMapper.java
  src/main/java/com/softserve/mapper/LessonsInScheduleMapper.java
  src/main/java/com/softserve/mapper/LessonsListInRoomScheduleMapper.java
  src/main/java/com/softserve/mapper/RoomTypeMapper.java
  src/main/java/com/softserve/mapper/ScheduleForRoomMapper.java
  src/main/java/com/softserve/mapper/ToEven.java
  src/main/java/com/softserve/mapper/ToGroupInRoom.java
  src/main/java/com/softserve/mapper/ToList.java
  src/main/java/com/softserve/mapper/ToOdd.java
  src/main/java/com/softserve/mapper/ToRoomDto.java
  src/main/java/com/softserve/repository/ScheduleRepository.java
  src/main/java/com/softserve/repository/impl/ScheduleRepositoryImpl.java
  src/main/java/com/softserve/service/ScheduleService.java
  src/main/java/com/softserve/service/impl/ScheduleServiceImpl.java
  src/test/java/com/softserve/controller/ScheduleControllerTest.java
  src/test/java/com/softserve/service/ScheduleServiceTest.java
Labels: backend

#151 Backend/AddCaching
  README.md
  build.gradle
  src/main/java/com/softserve/config/CacheConfiguration.java
  src/main/java/com/softserve/service/impl/LessonServiceImpl.java
  src/main/java/com/softserve/service/impl/ScheduleServiceImpl.java
  src/main/java/com/softserve/service/impl/SemesterServiceImpl.java
  src/main/resources/cache.properties
Labels: backend

#161 Backend/BugFix/GroupedLessonUpdate
  src/main/java/com/softserve/repository/LessonRepository.java
  src/main/java/com/softserve/repository/impl/LessonRepositoryImpl.java
  src/main/java/com/softserve/service/impl/LessonServiceImpl.java
Labels: bug, backend

#164 Backend/Bugfix/TeacherControllerTest fix
  src/test/java/com/softserve/controller/TeacherControllerTest.java
  src/test/resources/create-teachers-before.sql
Labels: bug, backend

#169 Backend/BugFix/FixScheduleForRoomMapper
  src/main/java/com/softserve/controller/ScheduleController.java
  src/main/java/com/softserve/dto/DaysOfWeekWithClassesForRoomDTO.java
  src/main/java/com/softserve/dto/LessonsInRoomScheduleDTO.java
  src/main/java/com/softserve/dto/LessonsListInRoomScheduleDTO.java
  src/main/java/com/softserve/dto/ScheduleForRoomDTO.java
  src/main/java/com/softserve/entity/Room.java
  src/main/java/com/softserve/mapper/ConverterToSchedulesInRoom.java
  src/main/java/com/softserve/mapper/GroupMapper.java
  src/main/java/com/softserve/mapper/LessonsListInRoomScheduleMapper.java
  src/main/java/com/softserve/mapper/ScheduleForRoomMapper.java
  src/main/java/com/softserve/service/impl/ScheduleServiceImpl.java
Labels: bug, backend

#144 TS-google-auth-link
  frontend/src/actions/auth.js
  frontend/src/components/Auth/Auth.js
  frontend/src/components/Auth/Auth.scss
  frontend/src/sagas/auth.js
Labels: ready to review, frontend
