Repository nromanen/Schedule, pull requests merged in 2022-06, with the labels that each got.

#232 Refactoring code regarding SonarCloud
  .github/workflows/build.yml
  .gitignore
  build.gradle
  src/main/java/com/softserve/controller/ArchiveController.java
  src/main/java/com/softserve/controller/AuthenticationController.java
  src/main/java/com/softserve/controller/RoomTypeController.java
  src/main/java/com/softserve/controller/ScheduleController.java
  src/main/java/com/softserve/controller/SemesterController.java
  src/main/java/com/softserve/controller/SubjectController.java
  src/main/java/com/softserve/controller/TeacherController.java
  src/main/java/com/softserve/controller/UserController.java
  src/main/java/com/softserve/entity/Room.java
  src/main/java/com/softserve/entity/Semester.java
  src/main/java/com/softserve/entity/Subject.java
  src/main/java/com/softserve/exception/DeleteDisabledException.java
  src/main/java/com/softserve/exception/EntityNotFoundException.java
  src/main/java/com/softserve/exception/FieldAlreadyExistsException.java
  src/main/java/com/softserve/exception/FieldNullException.java
  src/main/java/com/softserve/exception/SortingOrderNotExistsException.java
  src/main/java/com/softserve/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/softserve/mapper/LessonInfoMapper.java
  src/main/java/com/softserve/mapper/SubjectMapper.java
  src/main/java/com/softserve/repository/LessonRepository.java
  src/main/java/com/softserve/repository/impl/BasicRepositoryImpl.java
  src/main/java/com/softserve/repository/impl/GroupRepositoryImpl.java
  src/main/java/com/softserve/repository/impl/LessonRepositoryImpl.java
  src/main/java/com/softserve/repository/impl/RoomRepositoryImpl.java
  src/main/java/com/softserve/repository/impl/ScheduleRepositoryImpl.java
  src/main/java/com/softserve/repository/impl/SemesterRepositoryImpl.java
  src/main/java/com/softserve/repository/impl/StudentRepositoryImpl.java
  src/main/java/com/softserve/repository/impl/TemporaryScheduleRepositoryImpl.java
  src/main/java/com/softserve/security/jwt/JwtUserFactory.java
  src/main/java/com/softserve/service/PeriodService.java
  src/main/java/com/softserve/service/SemesterService.java
  src/main/java/com/softserve/service/TeacherService.java
  src/main/java/com/softserve/service/impl/LessonServiceImpl.java
  src/main/java/com/softserve/service/impl/PeriodServiceImpl.java
  src/main/java/com/softserve/service/impl/RoomServiceImpl.java
  src/main/java/com/softserve/service/impl/ScheduleServiceImpl.java
  src/main/java/com/softserve/service/impl/SemesterServiceImpl.java
  src/main/java/com/softserve/service/impl/StudentServiceImpl.java
  src/main/java/com/softserve/service/impl/TemporaryScheduleServiceImpl.java
  src/main/java/com/softserve/service/impl/UserServiceImpl.java
  src/main/java/com/softserve/util/Constants.java
  src/main/java/com/softserve/util/CsvFileParser.java
  src/main/java/com/softserve/util/PasswordGeneratingUtil.java
  src/main/java/com/softserve/util/temporary_notification/DeletePeriodVacationNotify.java
Labels: refactoring, backend, task

#235 Remove build war in workflow
  .github/workflows/build.yml
Labels: backend, task, technical debt

#238 Fix code style violations in test
  .github/workflows/build.yml
  build.gradle
  config/checkstyle/checkstyle.xml
  src/test/java/com/softserve/assertions/CustomMockMvcAssertions.java
  src/test/java/com/softserve/config/SecurityConfig.java
  src/test/java/com/softserve/config/SecurityWebApplicationInitializer.java
  src/test/java/com/softserve/controller/DepartmentControllerTest.java
  src/test/java/com/softserve/controller/GroupControllerTest.java
  src/test/java/com/softserve/controller/LessonsControllerTest.java
  src/test/java/com/softserve/controller/PeriodControllerTest.java
  src/test/java/com/softserve/controller/RoomControllerTest.java
  src/test/java/com/softserve/controller/RoomTypeControllerTest.java
  src/test/java/com/softserve/controller/ScheduleControllerTest.java
  src/test/java/com/softserve/controller/SemesterControllerTest.java
  src/test/java/com/softserve/controller/StudentControllerTest.java
  src/test/java/com/softserve/controller/SubjectControllerTest.java
  src/test/java/com/softserve/controller/TeacherControllerTest.java
  src/test/java/com/softserve/controller/UserControllerTest.java
  src/test/java/com/softserve/mapper/TeacherMapperTest.java
  src/test/java/com/softserve/service/DepartmentServiceTest.java
  src/test/java/com/softserve/service/GroupServiceTest.java
  src/test/java/com/softserve/service/LessonServiceTest.java
  src/test/java/com/softserve/service/PeriodServiceTest.java
  src/test/java/com/softserve/service/RoomServiceTest.java
  src/test/java/com/softserve/service/ScheduleServiceTest.java
  src/test/java/com/softserve/service/SemesterServiceTest.java
  src/test/java/com/softserve/service/StudentServiceTest.java
  src/test/java/com/softserve/service/SubjectServiceTest.java
  src/test/java/com/softserve/service/TeacherServiceTest.java
  src/test/java/com/softserve/service/UserServiceTest.java
  src/test/java/com/softserve/util/PasswordGeneratingUtilTest.java
  src/test/java/com/softserve/util/TranslatorTest.java
Labels: refactoring, backend
